package Enumerations;

public class PerkID {
    public static final int SpeedyBuilder = 1;
    public static final int MangleMaster = 2;
    public static final int ConservativeConstruction = 3;
    public static final int VanityBlueprints = 4;
    public static final int TerritoryMarkerBlueprints = 5;
    public static final int CraftingDeviceBlueprints = 6;
    public static final int StorageContainerBlueprints = 7;
    public static final int ResourceBundleBlueprints = 8;
    public static final int Miner = 9;
    public static final int Lumberjack = 10;
    public static final int PrecisionMining = 11;
    public static final int PrecisionLogging = 12;
    public static final int PickaxeExpert = 13;
    public static final int LoggingAxeExpert = 14;
    public static final int Lucky = 15;
    public static final int Health = 16;
    public static final int Mana = 17;
    public static final int SpeedyMiner = 18;
    public static final int SpeedyLogger = 19;
    public static final int SpeedyMedic = 20;
    public static final int HealingKitExpert = 21;
    public static final int ImmediateImprovement = 22;
    public static final int FrugalMedic = 23;
    public static final int DefensiveManeuver = 24;
    public static final int BlockingRecovery = 25;
    public static final int Evasiveness = 26;
    public static final int DeflectDamage = 27;
    public static final int PointBlankShot = 28;
    public static final int DualWielding = 29;
    public static final int BladePowerAttack = 30;
    public static final int BluntPowerAttack = 31;
    public static final int CalledShot = 32;
    public static final int CircleKick = 33;
    public static final int Cleave = 34;
    public static final int DeflectArrows = 35;
    public static final int Dodge = 36;
}
