
SELECT pc.PlayerID ,
       pc.CharacterName ,
       pc.HitPoints ,
       pc.LocationAreaTag ,
       pc.LocationX ,
       pc.LocationY ,
       pc.LocationZ ,
       pc.LocationOrientation ,
       pc.CreateTimestamp ,
       pc.MaxHunger ,
       pc.CurrentHunger ,
       pc.CurrentHungerTick ,
       pc.UnallocatedSP ,
       pc.NextSPResetDate ,
       pc.NumberOfSPResets ,
       pc.ResetTokens ,
       pc.NextResetTokenReceiveDate ,
       pc.HPRegenerationAmount ,
       pc.RegenerationTick ,
       pc.RegenerationRate ,
       pc.VersionNumber ,
       pc.MaxMana ,
       pc.CurrentMana ,
       pc.CurrentManaTick ,
       pc.RevivalStoneCount ,
       pc.RespawnAreaTag ,
       pc.RespawnLocationX ,
       pc.RespawnLocationY ,
       pc.RespawnLocationZ ,
       pc.RespawnLocationOrientation ,
       pc.DateLastForcedSPReset ,
       pc.DateSanctuaryEnds ,
       pc.IsSanctuaryOverrideEnabled,
       pc.STRBase,
       pc.DEXBase,
       pc.CONBase,
       pc.INTBase,
       pc.WISBase,
       pc.CHABase,
       pc.TotalSPAcquired,
       pc.DisplayHelmet,
       pc.BackgroundID
FROM dbo.PlayerCharacters pc
WHERE pc.PlayerID = :playerID